version: '3.8'

services:
  # The Frontend Container (Includes Nginx to serve React and proxy to backend)
  frontend:
    image: bharatkumar19030/bigbite-frontend:latest
    container_name: bigbite-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  # The Backend Container
  backend:
    image: bharatkumar19030/bigbite-backend:latest
    container_name: bigbite-backend
    ports:
      - "5000:5000"
    # This tells docker to look for the physical .env file on the EC2 server setup
    env_file:
      - ./backend/.env
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped
